Product/source/djangoShop/urls.py
from django.contrib import admin
from django.urls import path
from bcuser.views import index, logout, RegisterView, LoginView
from product.views import (
    ProductList, ProductCreate, ProductDetail,
    ProductListAPI, ProductDetailAPI
)
from order.views import OrderCreate, OrderList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('logout/', logout),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('product/', ProductList.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('product/<int:pk>/', ProductDetail.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('order/', OrderList.as_view()),

    path('api/product/', ProductListAPI.as_view()),
    path('api/product/<int:pk>/', ProductDetailAPI.as_view())
]

Product/source/product/models.py
from django.db import models

class Product(models.Model):
    name=models.CharField(max_length=256, verbose_name='상품명')
    price=models.IntegerField(verbose_name='상품가격')
    description=models.TextField(verbose_name='상품설명')
    stock=models.IntegerField(verbose_name='재고')
    register_date=models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')

    def __str__(self):
        return self.name
    
    class Meta:
        db_table='bootcampus_product'
        verbose_name='상품'
        verbose_name_plural='상품들'

Product/source/product/forms.py
from django import forms
from .models import Product

class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        },
        max_length=64, label='상품명'
    )

    price=forms.IntegerField(
        error_messages={
            'required': '상품가격을 입력해주세요.'
        }, label='상품가격'
    )

    description=forms.CharField(
        error_messages={
            'required': '상품설명을 입력해주세요.'
        }, label='상품설명'
    )

    stock=forms.IntegerField(
        error_messages={
            'required': '재고를 입력해주세요.'
        }, label='재고'
    )

    def clean(self):
        cleaned_data=super().clean()
        name=cleaned_data.get('name')
        price=cleaned_data.get('price')
        description=cleaned_data.get('description')
        stock=cleaned_data.get('stock')

        if not(name and price and description and stock):
            self.add_error('name', '값이 없습니다')
            self.add_error('price', '값이 없습니다')
            self.add_error('description', '값이 없습니다')
            self.add_error('stock', '값이 없습니다')

Product/source/order/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import RegisterForm # order의 RegisterForm
from product.models import Product
from bcuser.models import Bcuser
from .models import Order

from bcuser.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class OrderCreate(FormView):
    form_class = RegisterForm
    success_url = '/order/' # 또는 /product/

    def form_valid(self, form):
        # transaction.atomic(): 데이터베이스 트랜잭션을 시작함. 
        # 이 블록 내에서 수행되는 모든 데이터베이스 연산은 원자성(atomicity)을 가짐. 
        # 즉, 블록 내의 연산 중 하나라도 실패하면 모든 연산이 취소됨
        with transaction.atomic():
            # 폼 데이터에서 제품 ID를 가져와 해당 제품을 데이터베이스에서 조회
            prod = Product.objects.get(pk=form.data.get('product'))
            # 주문객체를 생성
            order = Order(
                quantity=form.data.get('quantity'), #제품의 재고량을 가져와서 저장
                product=prod, #제품아이디 저장
                # 요청의 세션에서 'user' 키로 저장된 이메일 주소를 가져와 
                # Bcuser 테이블에서 해당 이메일을 가진 사용자를 검색하여 저장
                bcuser=Bcuser.objects.get(email=self.request.session.get('user'))
            )
            # 주문사항 저장
            order.save()
            # 제품의 재고를 줄임
            prod.stock -= int(form.data.get('quantity'))
            # 제품의 변경사항 저장
            prod.save()
        return super().form_valid(form)
    
    # 폼의 데이터가 유효하지 않을 때 호출되는 메서드
    def form_invalid(self, form):
        # 해당 제품의 페이지로 리다이렉트
        return redirect('/product/' + str(form.data.get('product')))

    # 폼을 초기화하는 데 필요한 인자들을 반환하는 메서드
    def get_form_kwargs(self, **kwargs):
        kw = super().get_form_kwargs(**kwargs) # 기본 구현에서 반환되는 인자들
        # 추가로 request 객체를 포함
        # RegisterForm에서 request 객체를 사용할 수 있게 됨
        kw.update({
            'request': self.request
        })
        return kw
    
# 현재 세션에 있는 이메일에 해당하는 order객체를 필터링하여 주문 정보 가져옴
@method_decorator(login_required, name='dispatch')
class OrderList(ListView):
    # model=Order # 주문된 제품만 가져오므로 쿼리를 통해서 가져옴
    context_object_name='order_list'
    template_name='order.html'

    # bcuser__email : Order모델에 bcuser라는 외래키가 존재하므로 bcuser 필드의 email속성에 접근이 가능 
    def get_queryset(self, **kwargs):
        queryset=Order.objects.filter(bcuser__email=self.request.session.get('user'))
        return queryset
    
    




    
    

Product/source/product/views.py
from django.shortcuts import render
from .models import Product
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from .forms import RegisterForm
from order.forms import RegisterForm as OrderForm

from django.utils.decorators import method_decorator
from bcuser.decorators import admin_required

from .serializers import ProductSerializer
from rest_framework import mixins
from rest_framework import generics

# ListView : ListView를 사용하면 데이터베이스에서 목록을 가져와서 
# 템플릿에 어떤 데이터 타입이든 쉽게 전달하는 작업을 수행해줌 
class ProductList(ListView):
    model=Product
    context_object_name='product_list'
    template_name='product.html'
    #paginate_by=10 # 한페이지에 최대 10개의 상품 표시

@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name='register_product.html'
    form_class=RegisterForm
    success_url='/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'), 
            price=form.data.get('price'), 
            description=form.data.get('description'), 
            stock=form.data.get('stock') 
            )
        product.save()

        return super().form_valid(form)
    
class ProductDetail(DetailView):
    queryset = Product.objects.all()
    context_object_name='product'
    template_name='product_detail.html'

    # **kwargs : 함수에 정해지지 않은 매개변수의 가변갯수을 활요하여 오버라이딩함
    # 상세정보의 필드를 가변적으로 선택하여 보여줄수 있음
    def get_context_data(self, **kwargs):
        # 기본적인 Product의 데이터 가져오기
        context=super().get_context_data(**kwargs)
        # Order의 OrderForm에서 받아온 데이터 추가
        context['form']=OrderForm(self.request)
        return context


# GenericAPIView : RestFulAPI의 기본 동작을 제공 views
# ListModelMixin : views에서 필요로하는 메서드를 제공(여기에서는 list)
class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    # RestFulAPI 타입으로 Product데이터베이스 변환
    # serializer_class : Product데이터를 JSON 형태로 반환
    serializer_class=ProductSerializer 

    def get_queryset(self):
        # select * from Product order by;
        # Product의 모든 데이터를 id로 정렬하여 반환하라
        return Product.objects.all().order_by('id')
    
    def get(self, request, *args, **kwargs):
        #list() : ListModelMixin에서 제공
        return self.list(request, *args, **kwargs)

# Django REST framework (DRF)를 사용하여 특정 상품의 상세 정보를 제공하는 API 뷰
# RetrieveModelMixin은 특정 객체의 상세 정보를 반환하는 메서드 (retrieve)를 제공
class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer
    # 모든 Product 객체를 id 기준으로 정렬하여 반환
    def get_queryset(self):
        return Product.objects.all().order_by('id')

    # HTTP GET 요청이 들어올 때 실행될 메서드를 정의
    def get(self, request, *args, **kwargs): 
        # RetrieveModelMixin에 정의된 retrieve 메서드를 호출하여 특정 상품의 상세 정보를 반환
        return self.retrieve(request, *args, **kwargs)

Product/source/product/templates/base.html
<html>

<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <scrip src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
        </script>
        {% block header %}
        {% endblock %}
</head>

<body>
        <div class="container">
                {% block contents %}
                {% endblock %}
        </div>
</body>

</html>

Product/source/product/templates/product.html
{% extends "base.html" %}

{% load humanize %}

{% block header %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
  function product_detail(id) {
    $.ajax({
      url: "/api/product/" + id,
      success: function (result) {
        $("#product-" + id).popover({
          html: true,
          content: result.name + "<br/>" + result.price
        }).popover('show');
      }
    });
  }

  function product_leave(id) {
    $("#product-" + id).popover('hide');
  }

  $(document).ready(function () {
    // 여기에 문서 로드 후 실행할 JavaScript 코드 추가 가능
  });
</script>
{% endblock %}

{% block contents %}

<div class="container mt-5">
  <h1>Shopping Mall</h1>
  <p>Email: {{ email }}</p>
  <button class="btn" onclick="location.href='/register/'">회원가입</button>
  <button class="btn" onclick="location.href='/logout/'">로그아웃</button>
  <button class="btn" onclick="location.href='/login/'">로그인</button>

  <div class="row mt-5">
    {% for product in product_list %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <!-- <img src="이미지_경로" class="card-img-top" alt="상품 이미지"> -->
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">가격: {{ product.price|intcomma }} 원</p>
          <p class="card-text">등록날짜: {{ product.register_date|date:'Y-m-d H:i' }}</p>
          <a href="/product/{{ product.id }}" class="btn btn-primary">상품 상세 보기</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

Product/source/product/templates/product_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block contents %}
<div class="row mt-5">
  <div class="col-12">
    <div class="card" style="width: 100%;">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <form action="/order/create/" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              <!-- 상품설명(product)hidden 으로 설정 되었있으로 안보이도록 설정 -->
              {% if field.name != 'product' %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% endif %}
            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                placeholder="{{ field.label }}" name="{{ field.name }}"
                value="{% if field.name == 'product' %}{{product.id}}{% endif %}" />
	          </div>
              {% if field.errors %}
              <span style="color: red">{{ field.errors }}</span>
              {% endif %}
              {% endfor %}
          <button type="submit" class="btn btn-primary">주문하기</button>  
          </form>
        </li>
        <li class="list-group-item">가격: {{ product.price|intcomma }} 원</li>
        <li class="list-group-item">등록날짜: {{ product.register_date|date:'Y-m-d H:i' }}</li>
        <li class="list-group-item">재고: {{ product.stock|intcomma }} 개</li>
        <li class="list-group-item">{{ product.description|safe }}</li>
      </ul>
</div>
</div>
<div class="row">
<div class="col-12">
  <a href="/product/">목록보기</a>
</div>
</div>
{% endblock %}

Product/source/product/templates/register_product.html
{% extends "base.html" %}
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_description').summernote({
        height: 300
    });
   });
  </script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>상품 등록</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action=".">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% if field.name == 'description' %}
        <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
        {% else %}
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
      placeholder="{{ field.label }}" name="{{ field.name }}" />
        {% endif %}
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
      <button type="submit" class="btn btn-primary">생성</button>
    </form>
  </div>
</div>
{% endblock %}